name: pull github packages

on: push

jobs:
  pullPackages:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: scm checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        #registry-url: "https://npm.pkg.github.com/@ge-ren"
    - name: test
      run: |
        npm install @ge-ren/npm-sample-ga
        node index.js 
      env: 
        github-token: ${{ secrets.TOKEN }}
         
