name: pull github packages

on: 
  #push
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  github-token: ${{ secrets.TOKEN }}
jobs:
  pullPackages:
    runs-on: ubuntu-latest
 #     CI: true
    steps:
    - name: scm checkout
      uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: "https://npm.pkg.github.com"
    - name: test
      run: |
        echo ${{ env.github-token }}
        npm config list --json 
        npm install @ge-ren/npm-sample-ga@1.0.0
        node index.js 
         
